### ISSUE TITLE
Add fr-notices

### ISSUE THREAD

**Issue by ascott1** [eregs/eregs.github.io#4]
https://github.com/cfpb/fr-notices

**Comment by cmc333333** [comment]
We discussed this a bit in chat, so documenting here, edited to merge our soliloquies/threads of conversation 

@cmc333333 CFPB folks - what do you think about moving `fr-notices` over to the `eregs` organization? seems like few points of contention

@ascott1 should it be `cfpb-fr-notices` in that case?

@willbarton  Well, yeah… is there any advantage to having CFPB-specific fr-notices in the eregs org? or do you envision all  agency notices living together

@cmc333333 there's no reason the repo has to be cfpb specific? all agencies can live in that same repo. no collisions; one datastore

@willbarton I mean, I have no objections per se, I’m just not sure that’s sustainable

@cmc333333 why not?

@willbarton I think it would end up with agencies having their own anyway, and not necessarily pushing upstream. Looking back at our (cfpb) workflow over the past several months, fr-notice edits tend to be fairly succinct, and they’re part of a set of commits/prs that end up being more to do with the parser (and browser regression tests for the changes) than the notice XML changes. An extra step of PR’ing the upstream repo, after our fork would add extra effort to a fairly effortless task. Or it would encourage massive XML dumps at milestones along the way. I like the idea of having all the bespoke XML in one central place, and the idea that we could then see the sorts of changes everyone is having to make. and can therefore present them to the FR. idealistically, it seems right. I’m just a bit skeptical it’ll work in practice. I think laziness will win

@cmc333333 there's also deep value in a ​_shared_​ repository. Imagine if the parser fetched from that repo automatically. no need for everyone to have their own copy of fr-notices, no need to keep them all in sync manually

@willbarton would that make much of a difference if you’re having to edit the XML to get a good parse anyway? And, if you’re not having to edit the XML, then it fetches from the FR automatically already.  (playing devil’s advocate to tease out what could go wrong with this, fwiw. my objections are very slight, and I think it’s a good idea all around)

@cmc333333 right, but if you edit the xml, how does it get to adam?

@willbarton Right, Adam pulls fr-notices manually. (I presume, you do, @ascott1. :neutral_face:)

@cmc333333 so cfpb needs it's own fr-notices. and atf. and fec. and every agency? that seems terribly redundant and not newbie friendly. if we had a shared datastore, everyone would be on the same footing as often as desired

@willbarton Hmm. If it’s newbie-friendliness we’re looking for, I’m not sure more magic is a good thing. I was on the project for an embarrassingly long time before I figured out there’s a JSON API that it hits to get the fr-notices it needs. And even further along before I realized that ​_that’s_​ what the effective date is parsed from. For getting up and running, it sounds good. But when something goes wrong, you have to dig through all the automaticity to figure out what’s happening

@ascott1 hmm, is a git repo the right place to have that size of a data store?

@willbarton git gives us history of edits. i.e. blame

@ascott1 once we arrive upon canonical representations of all of the regs

@cmc333333 @willbarton: I disagree. Needing to know "oh I need to get this thing for CFPB, these things for ATF, .... for anything to work" seems more problematic. @ascott1 it's free and has history

@theresaanna I think you can mitigate having to dig through automaticity. I'm going to start sounding like a broken record about docs...

@willbarton @theresaanna: I agree. That’s kind of my point. Automaticity isn’t a solution for newbie-friendliness. Docs are

@theresaanna :+1:

@cmc333333 I don't think automation and docs are at odds? they seem unrelated. automation can certainly solve many newbie-friendly problems. as can docs

@theresaanna @cmc333333 agreed. automation + docs does = new person friendly. yeah, not everyone should need to know every piece of this thing to be able to work with it.

@ascott1 maybe a stupid reason, but if i discover an error in an old fr-notice, it would be frustrating to dig through every agency’s notice to find the right one. not opposed to this btw, just thinking it through aloud

@willbarton @ascott1 : well, they’re organized by fr doc number, so as long as you have that, you can find it

@ascott1 i could see separate repos for each agency and a single repo that pulls those in. i fear giant repos

@cmc333333 they could be federated, I suppose. I'm trying to avoid needing so much configuration

@willbarton @cmc333333: I think it’s a good idea. I really like the potential for sharing of solutions to common textual problems too, since every agency has to go through the federal register and their quaint XML conversion process.

@ascott1 :+1:

@cmc333333 yeah? when you have a chance, would you mind changing the ownership of the repo? we'll wipe out atf-specific version and PR to the shared once. the slightly longer term play for me is to keep everyone 18f-side in sync automatically. we get occasional problems when comparing output because we're using slightly different versions of the input files, which is maddening. Further, FEC's edits are currently being swapped back and forth between contractor machines which also drives me crazy. ​_there must be order_​

**Comment by cmc333333** [comment]
This has sat for a long while. I'm inclined to pull in all of CFPB's and ATF's docs into a non-forked repo. Yes/no? If there aren't any objections, I'll do this next week.

**Comment by ascott1** [comment]
:+1: @cmc333333

**Comment by cmc333333** [comment]
Done! https://github.com/eregs/fr-notices
